### ISSUE TITLE
GeoFire

### ISSUE THREAD

**Issue by joemerritt** [firebase/geofire-java#23] opened 2016-06-04 11:27 UTC
I may be missing something. But has GeoFire been updated to work with the new configuration of Firebase?

**Comment by nasznjoka** [comment] 2016-06-05 14:17
Not yet Geofire 1.1.0 requires the use of old firebase database implementation... It throws error on Context() and socan not be used.... I'm also waiting for the update

**Comment by joemerritt** [comment] 2016-06-05 14:19
Yep, driving me crazy... I wonder how many apps are not able to be updated due to this? Do you know of any other solutions?

**Comment by jwngr** [comment] 2016-06-06 06:52
Dupe of https://github.com/firebase/geofire-java/issues/18.

**Closed by jwngr** 2016-06-06 06:52 UTC
