### ISSUE TITLE
Multiple inserts

### ISSUE THREAD

**Issue by leonardo2204** [firebase/geofire-java#56] opened 2016-12-09 18:13 UTC
Hey guys, 
A common scenario using GeoFire is:

1. Save the Geo to a Collection
2. Grab the key (perhaps the object) and save it to another collection
3. You're done.

So, the problem that arise is, we can't guarantee the consistency in Firebase, e.g. if some error occurs in any of the steps.
In this case, Firebase provides `mDatabase.updateChildren(childUpdates);`.
My question is, what is the best scenario to handle this common situation with GeoFire ?

I was thinking about maybe exposing the updates HashMap as in [GeoFire](https://github.com/firebase/geofire-java/blob/master/src/main/java/com/firebase/geofire/GeoFire.java#L168):
```Java
Map<String, Object> updates = new HashMap<String, Object>();
        updates.put("g", geoHash.getGeoHashString());
        updates.put("l", Arrays.asList(location.latitude, location.longitude));
```
Or maybe creating another overloaded method receiving a HashMap, adding the `updates` to it and calling `mDatabase.updateChildren(childUpdates);`

Does it make sense ?

**Comment by vanniktech** [comment] 2017-11-27 15:20
I don't quite understand what you're trying to achieve. Can you elaborate a bit?

**Comment by samtstern** [comment] 2017-11-27 16:21
I believe the request here was to be able to add model data and geo data at the same time as an atomic batch.

**Comment by samtstern** [comment] 2017-11-27 16:22
Closing as duplicate of #51

**Closed by samtstern** 2017-11-27 16:22 UTC
